EXE=..\BIN\\

OBJ=..\obj\\

$(OBJ)A.OBJ:	A.C VM.H
	MSC A.C,$(OBJ)/AL;

$(OBJ)B.OBJ:	B.C VM.H
	MSC B.C,$(OBJ)/AL;

$(OBJ)C.OBJ:	C.C VM.H
	MSC C.C,$(OBJ)/AL;

$(OBJ)DGHIJ.OBJ:	DGHIJ.C VM.H
	MSC DGHIJ.C,$(OBJ)/AL;

$(OBJ)MNRSTX.OBJ:	MNRSTX.C VM.H
	MSC MNRSTX.C,$(OBJ)/AL;

$(OBJ)VM.OBJ:	VM.C VM.H
	MSC VM.C,$(OBJ)/AL;

$(OBJ)VMUTIL.OBJ:	VMUTIL.C VM.H
	MSC VMUTIL.C,$(OBJ)/AL;

$(EXE)VM.EXE:	$(OBJ)VM.OBJ	\
		$(OBJ)VMUTIL.OBJ\
		$(OBJ)A.OBJ	\
		$(OBJ)B.OBJ	\
		$(OBJ)C.OBJ	\
		$(OBJ)DGHIJ.OBJ \
		$(OBJ)MNRSTX.OBJ\
		MAKEFILE
	LINK $(OBJ)VM.OBJ+\
$(OBJ)VMUTIL+\
$(OBJ)A.OBJ+\
$(OBJ)B.OBJ+\
$(OBJ)C.OBJ+\
$(OBJ)DGHIJ.OBJ+\
$(OBJ)MNRSTX.OBJ,\
$(EXE)/EX;
